Add files via upload
Found some more errors in IntMap: intersect0
I commented out the original line and replaced it with my correction.

For both IntStack and IntMap, CLion gave me errors about the static variables
error: non-const static data member must be initialized out of line
I moved them to outside of the class and the error went away.

I was getting weird errors on IntMap.cpp: delete.
I think delete is a reserved word. Changed the function name to toDelete
Again I commented out the original line, copied it, and made the changes there.
I created .h files for them because IntMap needed to be pointed to IntStack so I added #include "IntStack.h" . This fixed the error.
However, even though I included #include "IntStack.h" in my IntList.h, it's giving me an unknown type name "IntStack". I don't know why.

My files are in cProlog/c_src